### ISSUE TITLE
Support ITK-Elastix as an alternative to SimpleITK with Elastix

### ISSUE THREAD

**Issue by yoda-vid** [sanderslab/magellanmapper#496]
We have used the SimpleITK with Elastix (formerly SimpleElastix) library for image registration (see #42, #379). Although this library has worked well, it is currently not available as a precompiled wheel with Elastix on PyPi. ITK-Elastix is a package available on PyPi that provides this access to Elastix, which would remove the requirement for the custom SimpleITK build that we currently provide. 

Since both SimpleITK and ITK-Elastix use ITK, they have similar APIs though with important caveats. Our goal will be to extend support for image registration using ITK-Elastix while maintaining support for SimpleITK and eventually making SimpleITK optional for MagellanMapper. Once we no longer require custom builds of SimpleITK, we can begin to make MagellanMapper available on PyPi as wel.

Goals of PRs in this series:
- [x] Support ITK-Elastix as an alternative to SimpleITK with Elastix (#495)
- [x] Maintain support for SimpleITK with Elastix
- [x] Make SimpleITK optional (#497)
- [x] Make ITK optional (#497)
- [x] Support groupwise registration in ITK-Elastix (see #438; #500)
