### ISSUE TITLE
Support more multiprocessed functions in Windows

### ISSUE THREAD

**Issue by yoda-vid** [sanderslab/magellanmapper#58]
Much of the multiprocessing work in MagellanMapper was designed to start by the ["fork" method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), which allows sharing memory for objects simply as global or class attributes. Fork mode is supported in Linux and macOS but not in Windows, which has prevented some tasks from completely in Windows without workarounds. We have been gradually adding support for the "spawn" mode, which requires additional handling to reduce memory utilization but is supported on all three major OSs and now the default in macOS as of Python 3.8.

Thus far, spawn mode is supported in MagellanMapper for blob detection, co-localization, and image transposition/downsampling. This issue will track support for additional tasks, including:
- [x] Atlas edge extension (labels erosion for watershed markers from `--register import_atlas` with lateral extension enabled) (fixed in #59)
- [x] Atlas volume metrics (`vol_stats`) (fixed in #60)
- [x] Make edge images (`make_edge_images`), only for label metrics (can turn off metrics by adding `fewerstats` atlas profile) (fixed in #60)
- [x] Edge-aware reannotation (`merge_atlas_segs`; fixed in #59 and #60)
- [x] Blob density map generation (`make_density_images`; fixed in #60)

Workarounds:
- These tasks can be run on Windows using Windows Subsystem for Linux, where forked mode is used. Currently, performance here is better in forked mode since objects can be shared directly without reloading data, pickling objects, or creating additional shared objects.
- `make_edge_images` and `merge_atlas_segs`: add `fewerstats` atlas profile to turn off volume stats

**Comment by yoda-vid** [comment]
Added a PR (#59) that fixes atlas edge extension with spawned multiprocessing.

**Comment by yoda-vid** [comment]
Added support for making edge images, density images, and volume stats in PR #60. Also turned off multiprocessing during atlas import lateral extension since it tended to slow performance slightly, presumably because it had to be restarted for each plane.
